version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-sandbag-go"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gkwn7477kk63"
s3_prefix = "lambda-sandbag-go"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "NotificationBucket=\"lambda-sandbag-go\" S3NotificationLambdaFunctionName=\"S3NotificationLambdaFunction\" Prefix=\"original/\""
image_repositories = []
